[project]
name = "notes"
version = "0.1.0"
description = "Personal notes and documentation"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.20",
]

[tool.uv]
dev-dependencies = []